{
 "title": "CGM TELEMETRY SYSTEM",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Sensor 2",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  unix_timestamp(time) AS \"time\",\n  value\nFROM observations\nWHERE\n  $__timeFilter(time) AND\n  sensor = \"fd00:0:0:0:202:2:2:2\"\nORDER BY time"
    }
   ]
  },
  {
   "title": "Sensor 3",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_add(time, interval 4 hour) AS \"time\",\n  value\nFROM observations\nWHERE\n  $__timeFilter(time) AND\n  sensor = \"fd00:0:0:0:203:3:3:3\"\nORDER BY time"
    }
   ]
  },
  {
   "title": "Sensor 4",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT\n  unix_timestamp(time) AS \"time\",\n  value\nFROM observations\nWHERE\n  $__timeFilter(time) AND\n  sensor = \"fd00:0:0:0:204:4:4:4\"\nORDER BY time"
    }
   ]
  },
  {
   "title": "Sensor 5",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT\n  unix_timestamp(time) AS \"time\",\n  value\nFROM observations\nWHERE\n  $__timeFilter(time) AND\n  sensor = \"fd00:0:0:0:205:5:5:5\"\nORDER BY time"
    }
   ]
  }
 ]
}